# Análisis y visualización de datos con Python
# 6. Limpieza de datos

    - a) Selección de observaciones y variables
    - b) Tipos de datos
    - c) Valores faltantes
    - d) Limpieza de texto
    - e) Limpieza de categóricos
    - f) Limpieza de números
    - g) Limpieza de fechas
    - h) Ordenar y guardar datos
    - i) Resumen

---

La limpieza de datos es el proceso de identificar, corregir o eliminar datos incorrectos, incompletos, irrelevantes o duplicados en un conjunto de datos. La limpieza de datos es importante para garantizar la precisión y la calidad de los datos y evitar errores en el análisis posterior. 

Empezaremos cargando los datos.

In [1]:
from numpy import nan
import pandas as pd

filename = 'data_raw/CNB_DOB_BPGS_Respuesta_Solicitud 332163723000249.xlsx'
df = pd.read_excel(filename, sheet_name="HBO", index_col='ID')
df

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_00001,S-D,acosta ortega teresa,acosta,ortega,teresa,1968-01-03 00:00:00,1968-01-03,37,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00002,S-D,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05 00:00:00,1968-01-05,58,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00003,S-D,arzate paredes juan,arzate,paredes,juan,1968-01-07 00:00:00,1968-01-07,83,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00004,S-D,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07 00:00:00,1968-01-07,86,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00005,S-D,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07 00:00:00,1968-01-07,88,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_07489,S-D,placenta,s-d,s-d,s-d,1982-06-05 00:00:00,1982-06-05,3079,15a,15A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07490,S-D,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05 00:00:00,1982-06-05,3060,32a,32A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07491,S-D,dedo de desconocido,s-d,s-d,s-d,1982-11-19 00:00:00,1982-11-19,6389,32a,32A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07492,S-D,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28 00:00:00,1982-11-28,6528,27a,27A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07493,S-D,osamenta de desconocido,s-d,s-d,s-d,1982-10-11 00:00:00,1982-10-11,5629,9a,9A,...,S-D,sin datos,S-D,S-D,Cadáver,semefo_df_bo_1982,251,156,no se recibio necropsia. es una osamenta.,desconocido

Cómo vimos anteriormente hay varios tipos de datos como: texto, numérico, fecha, etc.
De manera automática, Pandas infiere el tipo de datos al leer el archivo, de una manera muy similar a como Excel interpreta si un dato es texto, número o fecha.

Los tipos de datos de pandas son:
* `object`: texto o mezcla de varios tipos de datos, este es el tipo de dato por defecto
* `category`: información categórica, similar a Factors en R
* `int64`: números enteros
* `float64`: números con punto decimal
* `bool`: valores verdadero o falso
* `datetime64`: fechas
* `timedelta[ns]`: diferencias de tiempo

Podemos ver los tipos de datos inferidos usando la opción `.dtypes`.

Dependiendo del tipo de dato se pueden hacer diferentes operaciones y hay tipos de limpieza específica.

In [2]:
df.dtypes

Numero_progresivo_transcrito            object
Nombre_completo_transcrito              object
Primer_apellido                         object
Segundo_apellido                        object
Nombres_propios                         object
Fecha_transcrito                        object
Fecha_estandar                  datetime64[ns]
Expediente_SEMEFO_transcrito            object
Procedencia_transcrito                  object
Procedencia_estandar                    object
Procedencia_direccion                   object
Procedencia_alcaldia                    object
Numero_acta_transcrito                  object
Procedencia_acta                        object
Diagnostico_transcrito                  object
Diagnostico_estandar                    object
Diagnostico_extendido                   object
Sexo                                    object
Edad_transcrito                         object
Tipo_restos                             object
Bitacora_ingresos                       object
Pagina_PDF                               int64
Foja_transcrito                         object
Observaciones                           object
Conocido_desconocido                    object
dtype: object

## 6.a Estrategia de limpieza

En ciencia de datos, una variable limpia se refiere a una variable libre de errores, inconsistencias o artefactos no deseados que podrían comprometer el análisis. Esto significa que los datos son:

* Consistentes: siguen un formato uniforme
* Completos: los valores faltantes son rellenados, eliminados, imputados o ignorados.
* Precisos: libres de valores incorrectos, desactualizados o mal ingresados
* Válidos: cumplen con las restricciones esperadas, por ejemplo, tipo y rango
* Únicos: los duplicados se manejan según sea necesario.

En el caso de todas las variables es necesario revisar y tratar:
* Tipo de datos
* Valores faltantes
* Duplicados

Dependiendo de la variable es recomendable:
* Validar rangos y restricciones
* Detectar valores atípicos (outliers)
* Estandarizar y normalizar datos
* Validar datos categóricos
* Comprobar coherencia lógica

Para esto es recomendable revisar el conjunto de datos y el perfil de datos para generar una tabla de limpieza. Esta tabla incluye la variable, el tipo esperado, los pasos necesarios de limpieza y pasos de validación particulares a la variable.

Variable | Tipo | Limpieza | Validación
---------|------|----------|------------
ID | Alfanumérico |  | Patron: BO_19aa_ddddd
Numero_progresivo_transcrito | Texto | quitar S-D | original
Nombre_completo_transcrito | Texto |  | original
Primer_apellido | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Segundo_apellido | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Nombres_propios | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Fecha_transcrito | Texto |  | original
Fecha_estandar | Fecha | regenerar to_datetime | rango
Expediente_SEMEFO_transcrito | Texto |  | original
Procedencia_transcrito | Texto | quitar acentos, espacios extra, pasar minúsculas | original
Procedencia_estandar | Catálogo | regenerar y estandarizar cat_proc_sustitucion | verificar en catálogo
Numero_acta_transcrito | Texto |  | original
Procedencia_acta | Alfanumérico | quitar | 
Diagnostico_transcrito | Texto |  | original
Diagnostico_estandar | Catálogo | regenerar estandarizar cat_diag_sustitucion | verificar en catálogo
Sexo | Catálogo |  | verificar en catálogo
Edad_transcrito | Texto |  | original
Edad_estandar | Numérico | regenerar to_numeric | rango
Tipo_restos | Catálogo | quitar baja frecuencia | verificar en catálogo
Bitacora_ingresos | Catálogo |  | verificar en catálogo
Pagina_PDF | Numérico | quitar | 
Foja_transcrito | Texto | quitar | 
Observaciones | Texto | quitar | 
Conocido_desconocido | Catálogo | verificar S-D | verificar en catálogo

Una consideración importante es si se modificara la columna original o se generará una columna nueva con los datos limpios. Qué opción se escoge depende de varios factores, cómo el tamaño de la tabla o si nos interesa conservar la información original. En este tutorial crearemos columnas nuevas para poder contrastar los cambios y al final quitaremos las que no nos interesen.

### Ingeniería de atributos

Un proceso asociado a la limpieza es la ingeniería de atributos (feature engineering), en el cual se crean variables nuevas derivadas, transformando, agregando y combinando los datos ya existentes. Este proceso se puede hacer también durante el análisis de datos, dependiendo de lo que se necesite. 

Por ejemplo, se tiene la variable `Edad_transcrito`, la cual limpiaremos y guardaremos en la variable `Edad_estandar`. A partir de esta podemos obtener los grupos de edad y guardarlos en una nueva variable llamada `Edad_grupos`.

Al hacer la tabla de limpieza, es útil incluir las variables nuevas.

Variable | Tipo | Limpieza | Validación
---------|------|----------|------------
Fecha_año | Numérico |  | rango
Fecha_mes | Numérico |  | rango
Fecha_dia | Numérico |  | rango
Fecha_semana | Numérico |  | rango
Fecha_diasemana | Catálogo |  | verificar en catálogo
Procedencia_dirección | Catálogo | estandarizar cat_proc_sustitucion | verificar en catálogo
Procedencia_alcadía | Catálogo | estandarizar cat_proc_sustitucion | verificar en catálogo
Diagnostico_extendido | Catálogo | estandarizar cat_diag_sustitucion | verificar en catalogo
Edad_grupo | Catálogo | estandarizar con INEGI | verificar en catálogo

## 6.b Valores faltantes

Un valor faltante es un valor que falta o está incompleto en un conjunto de datos. A menudo, los valores faltantes se deben a errores de entrada de datos, fallas en la recolección de datos o problemas técnicos. Los valores faltantes pueden aparecer como espacios en blanco, ceros, letras u otros caracteres. La presencia de valores faltantes en un conjunto de datos puede afectar la precisión y la calidad del análisis de los datos, por lo que es importante identificarlos y manejarlos adecuadamente durante la limpieza y el preprocesamiento de los datos.

Por ejemplo, en el caso de los nombres podemos ver varios casos de datos faltantes.  Cada uno de estos representa diferentes tipos de falta de información y amerita un tratamiento diferente.
* "s-d": de acuerdo a la información proporcionada con el conjunto de datos, esto significa que el espacio que corresponde al nombre se encuentra vacío en las Bitácoras originales, y por lo tanto se transcribió como s-d para reflejar la falta de información de origen
* "desconocido" y "desconocida": en este caso, el SEMEFO desconoce la identidad del ingreso
* "Nombre de particular que podría encontrarse con vida. Se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.": en este caso el nombre se oculta por protección de datos personales
* `nan` esto sucede cuando la celda está vacía, en este caso no hay celdas vacías


La falta de información es, en sí misma, información sobre el conjunto de datos.

In [3]:
df['Nombre_completo_transcrito'].value_counts().head(10).to_frame()

                                                    count
Nombre_completo_transcrito
desconocido                                         12828
feto                                                 2610
Nombre de particular que podría encontrarse con...   2158
desconocida                                          1294
r. nacido                                             224
recien nacido                                         105
r. nacida                                              96
recien nacida                                          61
r nacido                                               34
osamenta                                               30

Podemos ver la cantidad de datos faltantes con el profile o la función `.isna()`

In [4]:
df.isna().sum()

Numero_progresivo_transcrito        0
Nombre_completo_transcrito          0
Primer_apellido                  1878
Segundo_apellido                  281
Nombres_propios                  2095
Fecha_transcrito                    0
Fecha_estandar                    266
Expediente_SEMEFO_transcrito        0
Procedencia_transcrito              0
Procedencia_estandar              408
Procedencia_direccion             437
Procedencia_alcaldia            31946
Numero_acta_transcrito              0
Procedencia_acta                25635
Diagnostico_transcrito              0
Diagnostico_estandar             8267
Diagnostico_extendido            8267
Sexo                                0
Edad_transcrito                     0
Tipo_restos                         0
Bitacora_ingresos                   0
Pagina_PDF                          0
Foja_transcrito                     0
Observaciones                   82723
Conocido_desconocido                0
dtype: int64

Para determinar si debemos de quitar filas por la cantidad de datos faltantes hay que analizar la cantidad de faltantes y su distribución.

**Nota** Explicación del comando
```
df.isna()         <-- determinar si las celdas son na
  .sum(axis=1)    <-- sumar los faltantes por fila
  .value_counts() <-- contar cuantas veces aparece cada número
  .sort_index()   <-- ordenar por el indice, que en este caso es el número de faltantes
```

In [5]:
df.isna().sum(axis=1).value_counts().sort_index()

0     9821
1    46700
2     7775
3    30780
4     1362
5      281
6      117
7        7
9        1
Name: count, dtype: int64

Cómo podemos ver, hay 406 filas donde faltan 5 o más valores. Revisemos estas filas. La mayor parte de los datos faltantes corresponden a casos donde se borraron los nombres para proteger datos personales, aunque también hay datos faltantes en las observaciones y el diagnóstico.

In [6]:
df[  df.isna().sum(axis=1)>4  ]

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_00842,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-02-08 00:00:00,1968-02-08,543,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1968,30,19 reverso,NaN,conocido
BO_1968_03002,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-04-22 00:00:00,1968-04-22,1170,H.E.V.,NaN,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,101,73 reverso,NaN,conocido
BO_1968_03007,S-D,Nombre de particular que podría encontrarse co...,NaN,s-d,NaN,1968-04-06 00:00:00,1968-04-06,1386,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,102,74,NaN,conocido
BO_1968_03145,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-07-18 00:00:00,1968-07-18,2561,Cruz Roja,CR,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,106,76,NaN,conocido
BO_1969_01269,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1969-01-03 00:00:00,1969-01-03,42,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Feto,semefo_df_bo_1969,44,30,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_07407,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-02 00:00:00,1982-07-02,3109,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07408,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-08 00:00:00,1982-07-08,3809,32a,32A,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07409,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-10 00:00:00,1982-07-10,3831,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07450,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-11-06 00:00:00,1982-11-06,6095,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,249,154 reverso,NaN,conocido
BO_1982_07474,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-12-15 00:00:00,1982-12-15,6897,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,249,154 reverso,NaN,conocido

## 6.c Eliminación de observaciones y variables

Es posible que no todos los datos contenidos en el conjunto de datos sean utilizables o de interés. Eliminarlos facilita el análisis y eficientiza el uso de memoria.

Algunas razones para eliminar filas o columnas son:
* Baja variabilidad, por ejemplo una columna donde todos los valores son iguales
* Información repetida, por ejemplo filas idénticas
* Gran cantidad de datos faltantes
* Información no relevante para el análisis.

Existen diversas estrategias para abordar tratar los datos faltantes, dependiendo del tipo de datos, cantidad de faltantes, distribución de la variable y el contexto del análisis. Las dos principales estrategias son la **eliminación** de las filas y/o columnas con datos faltantes y la **imputación** de valores faltantes.

Algunos ejemplos de imputación
* Reemplazan los valores nulos con un valor arbitrario (0, -1, "desconocido", etc.)
* Crear una nueva categoría indicando que el valor está ausente
* Imputación con estadísticos media (sin sesgo), mediana (con sesgo), moda(categórico)
* Imputación basada en modelos estimando el valor
* Interpolación temporal

En este tutorial usaremos una estrategia donde primero revisaremos los datos, marcaremos las columnas a quitar, y las quitaremos todas al final. Sin embargo, se indican comandos útiles para quitar filas.

### Datos duplicados

Es importante verificar si hay datos duplicados, ya que estos pueden ser señal de errores durante la generación de datos o causar errores en el análisis.
Podemos hacer esto con `.duplicated(keep=False)`. 
Es importante notar que aunque el indice sea único, si se detectan lineas duplicadas.

In [7]:
df[ df.duplicated(keep=False) ]

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_01734,S-D,gomez caballero pedro,gomez,caballero,pedro,1968-07-11 00:00:00,1968-07-11,2480,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,60,39,NaN,conocido
BO_1968_01736,S-D,gomez caballero pedro,gomez,caballero,pedro,1968-07-11 00:00:00,1968-07-11,2480,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,60,39,NaN,conocido
BO_1968_02175,S-D,desconocido,s-d,s-d,s-d,1968-07-11 00:00:00,1968-07-11,2479,11a Del.,11A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,74,49,NaN,desconocido
BO_1968_02177,S-D,desconocido,s-d,s-d,s-d,1968-07-11 00:00:00,1968-07-11,2479,11a Del.,11A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,74,49,NaN,desconocido
BO_1968_02595,S-D,desconocido,s-d,s-d,s-d,1968-12-03 00:00:00,1968-12-03,4393,1a Del.,1A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,88,56 reverso,NaN,desconocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_05377,S-D,sanchez carranza isaias,sanchez,carranza,isaias,1982-10-12 00:00:00,1982-10-12,5657,HB,HTB,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_05378,S-D,suarez hernandez jesus,suarez,hernandez,jesus,1982-10-11 00:00:00,1982-10-11,5644,15a,15A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_05379,S-D,salazar patino javier,salazar,patino,javier,1982-10-09 00:00:00,1982-10-09,5589,1a,1A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_07188,S-D,desconocido,s-d,s-d,s-d,S-D,NaT,S-D,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,239,144,NaN,desconocido
BO_1982_07206,S-D,desconocido,s-d,s-d,s-d,S-D,NaT,S-D,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,239,144,NaN,desconocido

En este caso no encontramos varios tipos de duplicados. En algunos casos parecen ser personas que aparecen varias veces y que tienen todos los datos, incluido el nombre completo, idénticos. Por otro lado, hay casos, como los desconocidos, donde hay una gran falta de información de origen, por lo que el hecho de que las filas sean duplicadas puede ser un indicador de la falta de información, la cual impide distinguir los casos. 

En este caso, dado que no podemos distinguir la razón de la duplicación de filas y que nos interesa analizar un conjunto de datos histórico, no quitaremos filas. Sin embargo, es posible quitar filas y columnas duplicadas con el comando: `.drop_duplicates()`

### Gran cantidad de faltantes

Una razón para quitar variables o filas es por qué hay una gran cantidad de faltantes. Una métrica general es quitar las variables en las que falta más del 10% de los datos, aunque es recomendable revisar cuáles son antes de hacer esta operación.

En este caso, marcaremos que las columnas a quitar son `Procedencia_alcaldia`, `Procedencia_acta` y `Observaciones` y las quitaremos más adelante.

In [8]:
df.isna().sum() / df.shape[0] * 100

Numero_progresivo_transcrito     0.000000
Nombre_completo_transcrito       0.000000
Primer_apellido                  1.939201
Segundo_apellido                 0.290157
Nombres_propios                  2.163273
Fecha_transcrito                 0.000000
Fecha_estandar                   0.274669
Expediente_SEMEFO_transcrito     0.000000
Procedencia_transcrito           0.000000
Procedencia_estandar             0.421296
Procedencia_direccion            0.451241
Procedencia_alcaldia            32.987072
Numero_acta_transcrito           0.000000
Procedencia_acta                26.470406
Diagnostico_transcrito           0.000000
Diagnostico_estandar             8.536409
Diagnostico_extendido            8.536409
Sexo                             0.000000
Edad_transcrito                  0.000000
Tipo_restos                      0.000000
Bitacora_ingresos                0.000000
Pagina_PDF                       0.000000
Foja_transcrito                  0.000000
Observaciones                   85.418818
Conocido_desconocido             0.000000
dtype: float64

Otra situación es cuando la columna o fila solo tiene algunos faltantes, en este caso es necesario tomar decisiones dependiendo de la situación. Por ejemplo, en el caso de la columna 'Numero_progresivo_transcrito' el 72% de los datos son 'S-D', es decir, no hay datos. Dado que nuestro estudio se centra en describir la población y no los procesos administrativos, y la gran cantidad de variables, podemos ignorarla.

In [9]:
df['Numero_progresivo_transcrito'].value_counts(normalize=True).head(5)

Numero_progresivo_transcrito
S-D    0.719435
41     0.001136
38     0.001136
37     0.001126
40     0.001126
Name: proportion, dtype: float64

Por otro lado, en el caso de la columna 'Edad_transcrito' el 58% de los datos son 'S-D', es decir, no hay datos. Sin embargo, esta variable es de gran interés, por lo que la procesaremos para obtener la mayor cantidad de edades posibles y usarla en el análisis.

In [10]:
df['Edad_transcrito'].value_counts(normalize=True).head(5)

Edad_transcrito
S-D    0.585075
40     0.017843
30     0.017668
35     0.017203
25     0.016707
Name: proportion, dtype: float64

El comando `dropna()` sirve para quitar filas (`axis=0`) o columnas (`axis=1`). Existen varias opciones:

* `how='any'` quita las filas o columnas donde hay al menos un `nan`, este parámetro es el default
* `how='all'` quita las filas o columnas donde todos son `nan`
* `thresh=numero` quita las filas o columnas con más de cierto número de `nan`s, esto es útil para detectar automáticamente columnas donde faltan muchos datos

El siguiente comando quita automáticamente las columnas con más del 10% de faltantes.

```
df = df.dropna(thresh=round( df.shape[0]*0.10), axis=1)
```

### Información no relevante

Los conjuntos de datos muchas veces contienen información que no es relevante para el análisis. Para determinar si la información es relevante o no es necesario tener clara la pregunta de investigación y los objetivos del análisis.

Por ejemplo, en este curso nos interesa analizar las características demográficas de los ingresos al SEMEFO. Por lo tanto, columnas que describen variables demográficas cómo 'Edad' y 'Sexo' son de gran interés. Por otro lado, columnas cómo 'Numero_progresivo_transcrito' o 'Pagina_PDF', las cuales describen la localización en la bitácora y el proceso administrativo, no son de interés.

Además, en este tutorial regeneraremos las columnas de datos estandarizadas cómo 'Procedencia_estandar' y 'Diagnostico_estandar', por lo cual eliminaremos estas columnas.

Para esto usaremos el comando `.drop()`. Recuerda que el parámetro `axis=0` se refiere a filas y `axis=1` a columnas.

Para guardar estas modificaciones debemos de actualizar el dataframe. Recuerda verificar antes de eliminar información.

In [11]:
col_drop = [
            'Numero_progresivo_transcrito', 'Fecha_estandar', 'Procedencia_estandar',
            'Procedencia_direccion', 'Procedencia_alcaldia','Procedencia_acta', 
            'Diagnostico_estandar', 'Diagnostico_extendido', 'Bitacora_ingresos', 
            'Pagina_PDF', 'Foja_transcrito', 'Observaciones', 
           ]
df = df.drop( col_drop, axis=1)
df.head()

,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Numero_acta_transcrito,Diagnostico_transcrito,Sexo,Edad_transcrito,Tipo_restos,Conocido_desconocido
ID,,,,,,,,,,,,,
BO_1968_00001,acosta ortega teresa,acosta,ortega,teresa,1968-01-03 00:00:00,37,S-D,S-D,S-D,Femenino,S-D,Cadáver,conocido
BO_1968_00002,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05 00:00:00,58,S-D,S-D,S-D,Femenino,S-D,Cadáver,conocido
BO_1968_00003,arzate paredes juan,arzate,paredes,juan,1968-01-07 00:00:00,83,S-D,S-D,S-D,Masculino,S-D,Cadáver,conocido
BO_1968_00004,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07 00:00:00,86,S-D,S-D,S-D,Masculino,S-D,Cadáver,conocido
BO_1968_00005,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07 00:00:00,88,S-D,S-D,S-D,Femenino,S-D,Cadáver,conocido

## 6.d Limpieza de texto

En este conjunto las columnas de texto son:
* 'Primer apellido'
* 'Segundo Apellido'
* 'Nombre(s)'
* 'Nombre completo'
* 'Institución_origen'
* 'Rdoc'

In [ ]:
col_str = ['Primer apellido', 'Segundo Apellido', 'Nombre(s)',  
           'Nombre completo', 'Institución_origen']

# Este comando obtiene para cada columna de interes los cinco valores mas comunes
# y los despliega para poder revisar los datos
for col in col_str:
    print(col)
    display( df[col].value_counts(dropna=False).index.tolist()[0:5] )

Dentro de estos datos tenemos varios tipos de valores que nos representan distintos tipos de datos faltantes.

Estos son:
* `nan`
* `'  '`
* 'Nombre de particular que se encuentra con vida, se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.  '

Generalmente, podemos sustituir estos valores por `nan`, por un string vacio `''`o por un string especial cómo 'S/D' o 'Confidencial'.

En este caso vamos a sustituir por un string vacio: `''`

En primer lugar vamos a sustituir todos los `nan` usando el comando `.fillna()`.

In [ ]:
# esta operación solo se aplica y guarda sobre las columnas de texto
df[col_str] = df[col_str].fillna('')

for col in col_str:
    print(col)
    display( df[col].value_counts(dropna=False).index.tolist()[0:5] )

Ahora, vamos a remplazar los demas valores especiales:

* `'  '` --> `''`
* 'Nombre de particular que se encuentra con vida, se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.  ' --> 'Confidencial'

En este caso crearemos un diccionario de remplazos y usaremos la función `.replace()`

In [ ]:
replace_str = {'  ':'',
               'Nombre de particular que se encuentra con vida, se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.  ':'Confidencial'
              }

# remplazamos con un for loop columna por columna, en lugar de usar selección
# esto es solo por ejemplo

for col in col_str:
    print('Remplazando columna:', col)
    df[col] = df[col].replace(replace_str)
    # veamos los cinco valores mas comunes de la columna despúes de la sustitución
    display( df[col].value_counts(dropna=False).index.tolist()[0:5] )

Dependiendo del tipo de dato se pueden hacer diferentes operaciones. Por ejemplo, se puede pasar a mayusculas un texto pero no un número, se puede obtener el año de una fecha pero no de un texto

Por ejemplo, pensemos que queremos que las instituciones de origen no esten todas en mayusculas, sino solo la primera letra de la palabra.

Para hacer esto seleccionaremos la columna de interes, y luego aplicaremos la función `.str.title()`. 

**Nota**: existen varias funciones para mayusculas y minusculas como `.upper()`, `.lower()`, `.capitalize()` y `.title()`

In [ ]:
df['Institución_origen'].str.title()

Existen funciones que no se encuentran en pandas pero que pueden ser utiles. Por ejemplo, para quitar los acentos es posible con la función `unidecode()`, la cual es parte de la biblioteca `unidecode`.

In [ ]:
from unidecode import unidecode
unidecode('México')

Podemos aplicar esta función a toda la columna, en este caso usaremos apply, ya que no es una función default de pandas

In [ ]:
df['Institución_origen'].apply( unidecode )

Además, podemos aplicar varias funciones juntas.

In [ ]:
df['Institución_origen'].str.title().apply(unidecode)

Estas modificaciones son temporales. Para guardar los resultados es necesario guardar la columna o serie generada. Esto puede ser en una nueva columna o en la misma columna

In [ ]:
df['Institución_origen'] = df['Institución_origen'].str.title().apply(unidecode)
df.tail()

EL aplicar la función `unidecode()` a la columna puede genera un error si hay nans `AttributeError: 'float' object has no attribute 'encode'`. 
Esto se debe a que la columna incluye valores vacios, los cuales son de tipo `float`, por lo tanto la función `unidecode` falla, ya que los números no tienen acentos.

Dejo aqui una posible solución. Esta solución utiliza funciones lambda, las cuales son un tema avanzado más allá de este tutorial.

In [ ]:
df['Nombre(s)'].apply( lambda s: unidecode(s) if type(s)==str  else s )

Otra posible limpieza es quitar espacios al principio y final del texto, o cambiar tabuladores, saltos de página o múltiples espacios por uno solo. 
Este tipo de ocurrencias son dificiles de ver en el texto como humanos, sin embargo un espacio adicional al final de una palabra es suficiente para volverla un string diferente para la computadora. Por ejemplo, veamos este texto que incluye múltiples espaciós, tabuladores y saltos de linea.

In [ ]:
texto = "  Emanuel\tJurado     Sánchez \n "
print(texto)

La función `.strip()` quita los espacios adicionales del principio y final de un string.

In [ ]:
print(texto.strip())

Otra opción es combinar la función `.split()` y `.join()`.
La función `.split()` separa un texto en una lista, por default hace esto en los caracteres de espacio, pero se le pueden dar instrucciones de separar en caracteres específicos, por ejemplo en una coma `,`.
La función  `str.join()` une una lista con un caracter específico para generar un solo string.

En este caso estamos separando el texto en los espacios, para convertirlo en una lista de palabras. Despúes, esta lista se une con espacios.

In [ ]:
print(   ' '.join( texto.split() )   )

Es común que una limpieza requiera varios pasos. En ese caso podemos generar una función que incluya todos los pasos.

In [ ]:
def limpiar_texto(s):
    # checar el tipo
    if type(s)==str: # esto solo se ejecutará si es un string
        ### aqui agrega tus pasos de limpieza 
        s = unidecode(s) #quitar acento
        s = ' '.join( s.split() ) #quitar espacios extra
        s = s.title() #primera letra en mayuscula
    else: # esto se ejecutará si NO es un string
        s = s #devolveremos la entrada sin modificaciones, pero puedes cambiar esto
    return s
    
limpiar_texto(texto)

Ahora aplicaremos la función en las columnas de interes.

In [ ]:
for col in col_str:
    print('Limpieza de texto:', col)
    df[col] = df[col].apply( limpiar_texto )
df.tail()

## 6.e Limpieza de categóricos

En general se considera que un dato es categorico cuando hay pocas posibilidades definidas. Una aproximación rápida es que tenga menos de diez opciones de texto. Sin embargo esta no es una regla dura, por ejemplo el catálogo del INEGI de Estados, Municipios y Localidades tiene miles de opciones.


En este conjunto las columnas de texto son:
* 'Panteón_origen', 
* 'Estatus_FC', 
* 'Restos_tipo', 
* 'Sexo', 
* 'Conocido_Desconocido'

In [ ]:
col_cat = ['Panteón_origen', 'Estatus_FC', 'Restos_tipo', 'Sexo', 'Conocido_Desconocido']

# este es el mismo comando que usamos para ver col_str, pero cambiamos la lista que se usará
for col in col_cat:
    print(col)
    display( df[col].value_counts(dropna=False).index.tolist() )

Podemos convertir una columna de tipo `object` a `category` con la función `.astype("category")`. 

En este ejemplo caso reescribiremos la columna para poder realizar varias operaciones.

In [ ]:
for col in col_cat:
    df[col] = df[col].astype("category")

Podemos ver que el tipo a cambiado

In [ ]:
df.dtypes

Una ventaja de usar `category` es que permite definir un orden diferente al alfabético o numérico. Por ejemplo, definamos un orden especial para el tipo de restos. Por default las categorías se ordenan alfabeticamente, pero esto se puede modificar.

In [ ]:
from pandas.api.types import CategoricalDtype

orden_restos = ['Cadáver', 'Restos humanos', 'Restos cremados', 'Restos óseos', 'Feto', 'Miembros']
orden_restos = CategoricalDtype(categories=orden_restos, ordered=True)
df['Restos_tipo'] = df['Restos_tipo'].astype( orden_restos )
df['Restos_tipo'].tail()

Ahora si ordenamos el dataframe se usará el orden especial qué hemos definido

In [ ]:
df.sort_values(by='Restos_tipo')

### Creando columnas categóricas

Cuando se generan nuevas variables de datos a partir de las existentes se le llama "creación de características" o "ingeniería de características" (en inglés, feature engineering). Es una técnica comúnmente utilizada en el análisis de datos para mejorar la precisión de los modelos de machine learning o para encontrar patrones y tendencias en los datos. La idea es generar nuevas variables a partir de las ya existentes que puedan ser más relevantes o informativas para el problema en cuestión.

Veamos las instituciones de origen:

In [ ]:
df['Institución_origen'].value_counts()

Podemos ver que los cadaveres provienen de Instituciones Judiciales como en INCIFO y la PGR, de escuelas públicas y privadas. Entonces, generemos una nueva columna con el tipo de institución de origen.

Para esto primero crearemos un diccionario que nos permita mapear las instituciones a su tipo.

In [ ]:
cat_tipo_inst = {
        'Instituto De Ciencias Forenses - Tribunal Superior De Justicia De La Ciudad De Mexico': 'Institución judicial',
        'Procuraduria General De La Republica': 'Institución judicial',
        'Universidad Nacional Autonoma De Mexico - Facultad De Medicina': 'Escuela pública',
        'Instituto Politecnico Nacional - Escuela Nacional De Medicina Y Homeopatia': 'Escuela pública',
        'Centro Cultural Universitario Justo Sierra': 'Escuela privada',
        'Universidad Westhill - Facultad De Medicina': 'Escuela privada',
        'Universidad Anahuac - Facultad De Ciencias De La Salud': 'Escuela privada',
        'The American British Cowdray Medical Center La.P.': 'Escuela privada',
        'Secretaria De La Defensa Nacional - Escuela Militar De Medicina': 'Escuela privada',
        'Universidad Popular Autonoma Del Estado De Puebla': 'Escuela privada',
        'Universidad Tominaga Nakamoto S.C. Escuela De Medicina Ciencias Basicas': 'Escuela privada',
        'Escuela De Medicina Saint Luke': 'Escuela privada',
        'Institucion De Asistencia Privada - Escuela Libre De Homeopatia De Mexico': 'Escuela privada',
        }

A continuación usaremos map para generar una nueva columna usando el mapeo.

Guardaremos el resultado de esta operación en una columna nueva llamada 'Tipo_institución_origen'

**Nota** `.replace()` y `.map()` son funciones que toman un diccionario y lo utilizan para remplazar los valores. Sin embargo, `.replace()` solo sustituye los valores en el diccionario y si algo no se encuentra el valor en el dict deja la celda sin modificar. Por otro lado `.map()` cambia todos los valores en el diccionario y si no se encuentran el el dict lo sustituye por `nan`, por lo cual es útil para filtrar valores no validos.

In [ ]:
df['Tipo_institución_origen'] = df['Institución_origen'].map(cat_tipo_inst)
df['Tipo_institución_origen'].value_counts(dropna=False)

Ahora, hay que volver este dato de tipo categórico

In [ ]:
df['Tipo_institución_origen'] = df['Tipo_institución_origen'].astype("category")
df['Tipo_institución_origen'].head()

### Wibblywobbly o catálogos por similitud

A veces es necesario estandarizar los datos antes de volverlos una categoría.

Por ejemplo, estos serie de datos esta basada en datos llenados a mano sobre el sexo de pacientes.

In [ ]:
serie_sexo = pd.Series( [' Masculino', '-', '?', 'F', 'Femenina', 'Femenino', 'Femenino y Masculino', 'I?','Ilegible', 
                         'Indeterminable', 'Indeterminado', 'M', 'M F', 'MAsculino', 'Maculino', 'Masculino', 'Masculino.', 
                         'N', 'S/D', 'femenina', 'femenino', 'ilegible', 'indeterminado', 'masculino', 's/d', 'sin dato' ] ) 
serie_sexo

En primer lugar tenemos que determinar cuales opciones incluir en el catalogo. Además, es necesario tomar decisiones de registros dobles como 'M F'. 
En este caso nos gustaría reducir las opciones a 'Femenino', 'Masculino' e 'Indeterminado', donde 'Indeterminado' incluira todos los casos donde haya duda.

Para lograr la estandarización se generá un diccionario de equivalencias, el cual se usa con la función `.replace()` o `.map()`. 

Este diccionario se puede escribir a mano cómo se hizo arriba o inferir utilizando `wibblywobbly`. Esta biblioteca toma un catálogo y un conjunto de datos y regresa que tanto se parecen los textos.

In [ ]:
import wibblywobbly as ww

cat_sexo = ['Femenino', 'Masculino', 'Indeterminado']
ww.map_list_to_catalog(serie_sexo, cat_sexo, reject_value='Indeterminado')

También es posible obtener directamente un diccionario de sustitución.

La opción `reject_value` permite establecer un valor default si no se encuentra un texto lo suficientemente similar en el catálogo.

In [ ]:
replace_sexo = ww.map_list_to_catalog(serie_sexo, cat_sexo, output_format="dictionary", reject_value='Indeterminado')
replace_sexo

Este diccionario tiene errores, los cuales se pueden arreglar manualmente.

In [ ]:
replace_sexo['M'] = 'Masculino'
replace_sexo['N'] = 'Indeterminado'
replace_sexo['I?'] = 'Indeterminado'
replace_sexo['Femenino y Masculino'] = 'Indeterminado'

replace_sexo

Ahora podemos remplazar, estandarizar y contar.

In [ ]:
serie_sexo = serie_sexo.replace( replace_sexo )
serie_sexo

In [ ]:
serie_sexo.value_counts(dropna=False)

Revisen la documentación en: https://github.com/mar-esther23/WibblyWobbly

## 6.f Limpieza de números

Existen dos tipos de datos númericos, enteros y flotantes. Los dos se comportan de forma muy similar.

En este conjunto de datos la columna `Edad` contiene numeros, sin embargo su tipo es `object` ya que hay edades como "18 semanas" que corresponden a fetos y neonatos.
Además, cuando cargamos específicamos que el tipo era `str`.

In [ ]:
df['Edad'].value_counts()

Por lo tanto, es necesario volver la edad a número. Esto se puede hacer con la función `.to_numeric()` o con `.astype()`.
Los datos que no se pueden convertir a número, por ejemplo '18 semanas', ya que generarán error. La función tiene varios parametros que nos pueden servir:
```
errors{‘ignore’, ‘raise’, ‘coerce’}, default ‘raise’
        If ‘raise’, then invalid parsing will raise an exception.
        If ‘coerce’, then invalid parsing will be set as NaN.
        If ‘ignore’, then invalid parsing will return the input.
```

Una primera aproximación es convertir obligar a que se convierta a número. Cómo los datos de semanas nos pueden ser utiles a futuro no vamos a rescribir la columna 'Edad', sino a generar una nueva columna 'Edad_int' con los resultados

In [ ]:
df['Edad_int'] = pd.to_numeric(df['Edad'], errors="coerce")
df['Edad_int'].unique()

Veamos las edades que no fueron convertidas por la operación:

In [ ]:
df.loc[ (df['Edad'].notna()) & (df['Edad_int'].isna()), ['Restos_tipo','Edad','Edad_int'] ].drop_duplicates()

La mayor parte de las edades en semanas son de fetos, mientras que las excepciones corresponden a rango. Dada la cantidad de faltantes ignoraremos estos datos. Sin embargo, es buena práctica revisar el resultado de las conversiones y donde fallo.

Ahora, veamos la distribución de edades:

In [ ]:
df['Edad_int'].describe()

Tenemos una persona de 101 años, esto podría ser un dato fuera de rango. 
En este caso vamos a poner un críterio para manejar problemas similares a futuro, si la persona tiene mas de cién años remplazaremos su edad por nan.
Para lograr esto seleccionaremos todas las celdas de personas de mas de cién años que están en la columna 'Edad_años' con _.loc[]_ y remplazaremos estos valores por NaN.
Esto debé de cambiar la edad máxima de nuestros datos.

In [ ]:
from numpy import nan

df.loc[ df['Edad_int']>=100,'Edad_int' ] = nan
df['Edad_int'].max()

Veamos las estadísticas de la columna 'Edad_años' usando `.describe()`, esta función es una alternativa rápida a un profile.

In [ ]:
df['Edad_int'].describe()

## 6.g Limpieza de fechas

Las fechas se encuentran en formato `datetime64`, lo cual incluye, fecha y hora.
Este formato sigue el patrón: `yyyy-mm-dd hh:mm:ss`

En este conjunto las columnas de texto son:
* 'Fecha_inhumación'
* 'Fecha_defunción'
* 'Marca_temporal'

In [ ]:
col_date = ['Fecha_inhumación', 'Fecha_defunción', 'Marca_temporal']

for col in col_date:
    print(col)
    display( df[col].value_counts(dropna=False).index.tolist()[0:5] )

Convertiremos las fechas a datetime con `to_datetime()` y veremos en que casos fracasa la función.
Guardaremos el resultado en una columna con el sufijo `_date`.

**Nota:** Para entender esta función es muy importante ver en donde se agrega el modificador que indica una nueva columna

In [ ]:
for col in col_date:
    print('Convirtiendo columna:' + col)
    df[col+'_date'] = pd.to_datetime(df[col], errors='coerce')
    display(df.loc[ (df[col].notna()) & (df[col+'_date'].isna()), [col, col+'_date'] ].drop_duplicates())

En este caso se puede ver que la conversión fallo solo en tres casos de la columna 'Fecha_defunción'. Cómo en estos casos falta información no es necesario hacer otra limpieza.

Usando este tipo de dato ahora es posible seleccionar por año, mes, día, hora y minuto usando los comandos:

* columna.dt.year
* columna.dt.month
* columna.dt.day
* columna.dt.hour
* columna.dt.minute
* columna.dt.dayofweek (numerico)
* columna.dt.weekday (nombre en ingles)
* columna.dt.dayofyear (numerico)
* columna.dt.weekofyear (numerico)

Agregaremos columnas para marcar el dia de la semana, del año y número de semana.

Es importante recordar que aplicaremos esto sobre las columnas procesadas con sufijo '_date'

In [ ]:
for col in col_date:
    col = col+'_date' #usemos columna modificada
    df[col+'_diasemana'] = df[col].dt.weekday
    df[col+'_diaaño'] = df[col].dt.dayofyear
    df[col+'_semanaaño'] = df[col].dt.weekofyear
df

Al agregar columnas es importante tomar en cuenta el tipo de dato. Por ejemplo, veamos las columnas de día de la semana. Estas asignan un número al día de la semana con Lunes=0 y Domingo=6.

In [ ]:
df['Marca_temporal_date_diasemana'].unique()

Editemos estas columnas para que tengan el día de la semana por su nombre y sean categóricos ordenados.

Lo primero es hacer un diccionario para sustituir los valores por el nombre del día de la semana.

In [ ]:
dic_semana = {0:'Lunes', 1:'Martes', 2:'Miercoles', 3:'Jueves',
              4:'Viernes', 5:'Sábado', 6:'Domingo'}

col_weekday = ['Fecha_inhumación_date_diasemana', 'Fecha_defunción_date_diasemana',
               'Marca_temporal_date_diasemana']

for col in col_weekday:
    df[col] = df[col].replace(dic_semana)
df

Ahora, generemos la categoría ordenada y transformemos las columnas a categórico.

In [ ]:
orden_semana = ['Lunes', 'Martes', 'Miercoles', 'Jueves',
                'Viernes', 'Sábado', 'Domingo']
orden_semana = CategoricalDtype(categories=orden_semana, ordered=True)

for col in col_weekday:
    df[col] = df[col].astype( orden_semana )
df.dtypes

## 6.h Ordenar y guardar datos

Antes de guardar los datos veamos las columnas, esto nos dará una idea de que hemos hecho.

In [ ]:
df.columns

Al agregar columnas estas se ponen al final, por lo que sería bueno ordenarlas. Además, las columnas de fecha originales se parecen mucho a las procesadas, excepto por el cambio de formato. Entonces, podríamos quitar las originales para hacer mas pequeña la tabla. Este también es un buen momento para arrepentirse, por ejemplo quitaremos las columnas de 'diaaño'.

Dependiendo del análisis podemos quitar columnas. Por ejemplo, la columna de `Marca_temporal` y sus columnas derivadas describen cuando se hizo la captura de la información del panteón al MFC. Esto es útil si nos interesa la información administrativa del Módulo, pero no si estamos interesados en los datos demográficos de los restos en Fosa común. Por lo tanto en este caso quitaremos estas columnas.

In [ ]:
df = df[['Panteón_origen', 'Estatus_FC', 
         'Fecha_inhumación_date', 'Fecha_inhumación_date_diasemana', 'Fecha_inhumación_date_semanaaño', 
         'Fecha_defunción_date', 'Fecha_defunción_date_diasemana', 'Fecha_defunción_date_semanaaño',
         'Restos_tipo', 'Sexo', 'Edad', 'Edad_int',  'Conocido_Desconocido',
         'Primer apellido', 'Segundo Apellido', 'Nombre(s)', 'Nombre completo',
         'Institución_origen', 'Tipo_institución_origen']]
df.tail()

Este es también un buen momento de cambiar los nombres de las columnas. 

**Nota** compara estos dos comandos para distinguir entre cambiar el orden de las columnas y en Nombre de estas.

In [ ]:
df.columns = ['Panteón_origen', 'Estatus_FC', 
              'Fecha_inhumación', 'Fecha_inhumación_diasemana', 'Fecha_inhumación_semanaaño', 
              'Fecha_defunción', 'Fecha_defunción_diasemana', 'Fecha_defunción_semanaaño',
              'Restos_tipo', 'Sexo', 'Edad', 'Edad_años',  'Conocido_Desconocido',
              'Primer_apellido', 'Segundo_Apellido', 'Nombres', 'Nombre_completo',
              'Institución_origen', 'Tipo_institución_origen']
df.tail()

Hagamos un nuevo profile para ver el comportamiento de los datos limpios

In [ ]:
#!pip install ydata_profiling

from ydata_profiling import ProfileReport

file_profile = "profiles/MFC_profile_clean.html"
prof = ProfileReport(df, minimal=True) 
prof.to_file(output_file=file_profile)

Es posible guardar los datos limpios que hemos obtenido de varias formas, podemos guardarlos como csv o excel usando los comandos `.to_csv()` y `.to_excel()`. Estos formatos tienen la ventaja de que son faciles de compartir. 

Nosotros guardaremos los datos limpios en la carpeta _data_clean_ como un csv, debido a que el tamaño de la base de datos es grande, puede ser complicado para manipularla en excel. Sin embargo, es posible abrir archivos csv usando excel.

Es muy importante no rescribir los datos originales y tratar de tener una carpeta para cada parte del proceso de análisis, para evitar perder información y poder reproducir confiablemente nuestros análisis.

In [ ]:
file_out = "data_clean/MFC_ActualizacionNov2022_clean.csv"
df.to_csv(file_out)

Una desventaja de guardar los archivos usando csv o excel, es que podemos perder el formato y los tipos de datos. Esto es importante sobretodo para tipos de datos como _datetime_. Una opción es guardar nuestros datos en un formato que sea facilmente interpretable para python, aunque este no se pueda trabajar con excel.

In [ ]:
from joblib import dump

file_out_pickle = "data_clean/MFC_ActualizacionNov2022_clean.pkl"

with open(file_out_pickle, 'wb') as f:
    dump(df, f)

## 6.i Resumen

**¡Gracias!**